apiVersion: v1
kind: Service
metadata:
  name: httpclient-service
  namespace: cncamp
  labels:
    app: httpclient
spec:
  selector:
    app: httpclient
  ports:
    - name: http-client
      port: 80
      targetPort: http-app
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: httpclient-service
#   namespace: cncamp
#   labels:
#     app: httpclient
# spec:
#   selector:
#     matchLabels:
#       app: httpclient
#   endpoints:
#     - port: http-app
